# this file will link some executable python program to ~/.local/bin folder.
V := @

help:
	$(V)echo "just open the file to check out!"

install:
	$(V)ln -sf ~/Downloads/Code/python/autorm ~/.local/bin/pyautorm

uninstall:
	$(V)rm -rf ~/.local/bin/pyautorm
